# permissions for end users to edit netscalerobservabilityexporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: netscalerobservabilityexporter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: netscaler-operator
    app.kubernetes.io/part-of: netscaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: netscalerobservabilityexporter-editor-role
rules:
- apiGroups:
  - netscaler.com
  resources:
  - netscalerobservabilityexporters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - netscaler.com
  resources:
  - netscalerobservabilityexporters/status
  verbs:
  - get
