apiVersion: citrix.com/v1alpha1
kind: CitrixCpxWithIngressController
metadata:
  name: citrixcpxwithingresscontroller-sample
spec:
  # Default values copied from <project_dir>/helm-charts/citrix-cpx-with-ingress-controller/values.yaml
  ADMSettings:
    ADMIP: null
    analyticsServerPort: 5557
    bandWidth: 1000
    bandWidthLicense: false
    cpxCores: null
    licenseEdition: PLATINUM
    licenseServerIP: null
    licenseServerPort: 27000
    loginSecret: null
    vCPULicense: false
  affinity: {}
  analyticsConfig:
    distributedTracing:
      enable: false
      samplingrate: 100
    endpoint:
      server: null
      service: null
    required: false
    timeseries:
      auditlogs:
        enable: false
      events:
        enable: false
      metrics:
        enable: false
        mode: avro
      port: 5563
    transactions:
      enable: false
      port: 5557
  bgpPort: null
  bgpSettings:
    bgpConfig:
    - bgpRouter:
        localAS: 100
        neighbor:
        - ASOriginationInterval: 10
          address: null
          advertisementInterval: 10
          remoteAS: 100
    required: false
  cic:
    image: '{{ .Values.cic.imageRegistry }}/{{ .Values.cic.imageRepository }}:{{ .Values.cic.imageTag
      }}'
    imageRegistry: quay.io
    imageRepository: citrix/citrix-k8s-ingress-controller
    imageTag: 1.32.7
    pullPolicy: IfNotPresent
    required: true
    resources: {}
  cpxBgpRouter: false
  cpxLicenseAggregator: null
  crds:
    install: false
    retainOnDelete: false
  daemonSet: false
  defaultSSLCertSecret: null
  disableAPIServerCertVerify: false
  disableOpenshiftRoutes: null
  entityPrefix: null
  exporter:
    image: '{{ .Values.exporter.imageRegistry }}/{{ .Values.exporter.imageRepository
      }}:{{ .Values.exporter.imageTag }}'
    imageRegistry: quay.io
    imageRepository: citrix/citrix-adc-metrics-exporter
    imageTag: 1.4.9
    ports:
      containerPort: 8888
    pullPolicy: IfNotPresent
    required: false
    resources: {}
  fullnameOverride: ""
  image: '{{ .Values.imageRegistry }}/{{ .Values.imageRepository }}:{{ .Values.imageTag
    }}'
  imagePullSecrets: []
  imageRegistry: quay.io
  imageRepository: citrix/citrix-k8s-cpx-ingress
  imageTag: 13.1-37.38
  ingressClass: null
  ingressIP: null
  ipam: false
  jsonLog: false
  kubernetesURL: null
  license:
    accept: false
  logLevel: INFO
  logProxy: null
  mgmtHttpPort: 9080
  mgmtHttpsPort: 9443
  nameOverride: ""
  namespaceLabels: null
  nitroReadTimeout: null
  nodeSelector:
    key: null
    value: null
  nsConfigDnsRec: null
  nsCookieVersion: "0"
  nsDnsNameserver: null
  nsGateway: 192.168.1.1
  nsHTTP2ServerSide: "OFF"
  nsIP: 192.168.1.2
  nsLbHashAlgo:
    hashAlgorithm: DEFAULT
    hashFingers: 256
    required: false
  nsProtocol: http
  nsSvcLbDnsRec: null
  openshift: false
  optimizeEndpointBinding: null
  podAnnotations: {}
  profileHttpFrontend: {}
  profileSslFrontend: {}
  profileTcpFrontend: {}
  pullPolicy: IfNotPresent
  rbacRole: false
  replicaCount: 1
  resources: {}
  routeLabels: null
  serviceAccount:
    create: true
  serviceAnnotations: {}
  servicePorts: []
  serviceSpec:
    externalTrafficPolicy: Cluster
    loadBalancerIP: null
    loadBalancerSourceRanges: []
  serviceType:
    loadBalancer:
      enabled: false
    nodePort:
      enabled: false
      httpPort: null
      httpsPort: null
  setAsDefaultIngressClass: false
  sslCertManagedByAWS: false
  tolerations: []
  updateIngressStatus: false
  
  
