apiVersion: v2
appVersion: 1.10.2
description: A Helm chart for Citrix ADC CPX with Citrix ingress Controller running as sidecar.
home: https://www.citrix.com
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
maintainers:
- email: priyanka.sharma@citrix.com
  name: priyankash-citrix
- email: subash.dangol@citrix.com
  name: subashd
name: citrix-cpx-with-ingress-controller
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
version: 1.10.2
