apiVersion: citrix.com/v1alpha1
kind: CitrixIngressController
metadata:
  name: citrixingresscontroller-sample
spec:
  # Default values copied from <project_dir>/helm-charts/citrix-ingress-controller/values.yaml
  adcCredentialSecret: null
  clusterName: null
  cncPbr: false
  coeConfig:
    distributedTracing:
      enable: false
      samplingrate: 100
    endpoint:
      server: null
    required: false
    timeseries:
      auditlogs:
        enable: false
      events:
        enable: false
      metrics:
        enable: false
        mode: avro
      port: 30002
    transactions:
      enable: false
      port: 30001
  crds:
    install: false
    retainOnDelete: false
  defaultSSLCertSecret: null
  entityPrefix: null
  exporter:
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.8
    ports:
      containerPort: 8888
    pullPolicy: IfNotPresent
    required: false
  ignoreNodeExternalIP: false
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.18.5
  imagePullSecrets: []
  ingressClass: null
  ipam: false
  kubernetesURL: null
  license:
    accept: false
  logLevel: INFO
  logProxy: null
  namespaceLabels: null
  nodeSelector:
    key: null
    value: null
  nodeWatch: false
  nsCookieVersion: "0"
  nsHTTP2ServerSide: "OFF"
  nsIP: x.x.x.x
  nsPort: 443
  nsProtocol: HTTPS
  nsSNIPS: null
  nsVIP: null
  openshift: false
  podIPsforServiceGroupMembers: false
  pullPolicy: IfNotPresent
  routeLabels: null
  serviceAccount:
    create: true
  serviceClass: null
  setAsDefaultIngressClass: false
  tolerations: []
  updateIngressStatus: false
  
  
