apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
##
## Base operator rules
##
# We need to get namespaces so the operator can read namespaces to ensure they exist
- apiGroups:
  - rbac.authorization.k8s.io
  verbs:
  - "*"
  resources:
  - clusterrolebindings
  - clusterroles
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
# We need to manage Helm release secrets
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"
# We need to create events on CRs about things happening during reconciliation
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

##
## Rules for citrix.com/v1alpha1, Kind: CitrixCpxWithIngressController
##
- apiGroups:
  - citrix.com
  resources:
  - citrixcpxwithingresscontrollers
  - citrixcpxwithingresscontrollers/status
  - citrixcpxwithingresscontrollers/finalizers
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - persistentvolumeclaims
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "*"

#+kubebuilder:scaffold:rules
