apiVersion: netscaler.com/v1
kind: NetscalerObservabilityExporter
metadata:
  name: netscalerobservabilityexporter-sample
spec:
  # Default values copied from <project_dir>/helm-charts/netscaler-observability-exporter/values.yaml
  elasticsearch:
    enabled: false
    indexprefix: null
    server: null
  headless: false
  image: '{{ .Values.imageRegistry }}/{{ .Values.imageRepository }}:{{ .Values.imageTag
    }}'
  imageRegistry: quay.io
  imageRepository: citrix/citrix-observability-exporter
  imageTag: 1.5.001
  json_trans_rate_limiting:
    enabled: false
    limit: 100
    queuelimit: 1000
    window: 5
  kafka:
    broker: null
    enabled: false
    topic: null
  license:
    accept: false
  nodePortRequired: false
  ns_tracing:
    enabled: false
    server: zipkin:9411/api/v1/spans
  pullPolicy: IfNotPresent
  replicas: 1
  splunk:
    authtoken: null
    enabled: false
    indexprefix: null
    server: null
  timeseries:
    enabled: false
    nodePort: 30002
  transaction:
    nodePort: 30001
  
  
