# permissions for end users to edit citrixingresscontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: citrixingresscontroller-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: citrix-ingress-controller-operator
    app.kubernetes.io/part-of: citrix-ingress-controller-operator
    app.kubernetes.io/managed-by: kustomize
  name: citrixingresscontroller-editor-role
rules:
- apiGroups:
  - citrix.com
  resources:
  - citrixingresscontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citrix.com
  resources:
  - citrixingresscontrollers/status
  verbs:
  - get
