apiVersion: citrix.com/v1alpha1
kind: CitrixIngressController
metadata:
  name: cic
spec:
  # Default values copied from <project_dir>/helm-charts/citrix-ingress-controller/values.yaml
  adcCredentialSecret: ""
  cicSettings:
    cicConfig:
      NS_COOKIE_VERSION: "0"
      NS_HTTP2_SERVER_SIDE: "OFF"
    required: false
  coeConfig:
    distributedTracing:
      enable: false
      samplingrate: 100
    endpoint:
      server: ""
    required: false
    timeseries:
      auditlogs:
        enable: false
      events:
        enable: false
      metrics:
        enable: false
        mode: avro
      port: 30002
    transactions:
      enable: false
      port: 30001
  crds:
    install: false
    retainOnDelete: false
  defaultSSLCertSecret: ""
  entityPrefix: ""
  exporter:
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.6
    ports:
      containerPort: 8888
    pullPolicy: IfNotPresent
    required: false
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.10.2
  ingressClass: ""
  ipam: false
  kubernetesURL: ""
  license:
    accept: false
  logLevel: INFO
  logProxy: ""
  namespaceLabels: ""
  nodeSelector:
    key: ""
    value: ""
  nodeWatch: false
  nsIP: x.x.x.x
  nsPort: 443
  nsProtocol: HTTPS
  nsVIP: ""
  openshift: false
  pullPolicy: IfNotPresent
  routeLabels: ""
  serviceAccount:
    create: true
  serviceClass: ""
  updateIngressStatus: false
  
  
