apiVersion: v1
kind: ConfigMap
metadata:
  name: cpx-{{ .Release.Name }}-configmap
data:
  LOGLEVEL: {{ .Values.logLevel | quote | lower }}
{{- if eq (upper .Values.nsProtocol) "HTTPS" }}
  NS_PROTOCOL: "https"
{{- if .Values.cpxBgpRouter }}
  NS_PORT: "9443"
{{- else }}
  NS_PORT: "443"
{{- end }}
{{- else }}
  NS_PROTOCOL: "http"
{{- if .Values.cpxBgpRouter }}
  NS_PORT: "9080"
{{- else }}
  NS_PORT: "80"
{{- end }}
{{- end }}

{{- if .Values.cicSettings.required }}
{{- with .Values.cicSettings.cicConfig }}
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}

{{- if .Values.coeConfig.required }}
  NS_ANALYTICS_CONFIG: |
    distributed_tracing:
      enable: {{ .Values.coeConfig.distributedTracing.enable | quote }}
      samplingrate: {{ .Values.coeConfig.distributedTracing.samplingrate }}
    endpoint:
      server: {{ include "analytics.server" . | quote }}
    timeseries:
      port: {{ .Values.coeConfig.timeseries.port }}
      metrics:
        enable: {{ .Values.coeConfig.timeseries.metrics.enable | quote }}
        mode: {{ .Values.coeConfig.timeseries.metrics.mode | quote }}
      auditlogs:
        enable: {{ .Values.coeConfig.timeseries.auditlogs.enable | quote }}
      events:
        enable: {{ .Values.coeConfig.timeseries.events.enable | quote }}
    transactions:
      enable: {{ .Values.coeConfig.transactions.enable | quote }}
      port: {{ .Values.coeConfig.transactions.port }}
{{- end }}

{{- if .Values.cpxBgpRouter }}
{{- if .Values.bgpSettings.required }}
  NS_BGP_CONFIG: |
{{- with .Values.bgpSettings.bgpConfig }}
    bgpConfig:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
