# permissions for end users to edit citrixcpxwithingresscontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: citrixcpxwithingresscontroller-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: citrix-cpx-with-ingress-controller-operator
    app.kubernetes.io/part-of: citrix-cpx-with-ingress-controller-operator
    app.kubernetes.io/managed-by: kustomize
  name: citrixcpxwithingresscontroller-editor-role
rules:
- apiGroups:
  - citrix.com
  resources:
  - citrixcpxwithingresscontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - citrix.com
  resources:
  - citrixcpxwithingresscontrollers/status
  verbs:
  - get
