# permissions for end users to view citrixcpxwithingresscontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: citrixcpxwithingresscontroller-viewer-role
rules:
- apiGroups:
  - citrix.com
  resources:
  - citrixcpxwithingresscontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - citrix.com
  resources:
  - citrixcpxwithingresscontrollers/status
  verbs:
  - get
