apiVersion: helm.operator-sdk/v1alpha1
kind: CitrixIngressController
metadata:
  name: example-cic
spec:
  # Default values copied from <project_dir>/helm-charts/citrix-ingress-controller/values.yaml
  
  nsIP: x.x.x.x
  image: registry.connect.redhat.com/citrix/citrix-ingress-controller:latest
  nsPort: 443
  nsProtocol: HTTPS
  nsVIP: null
  openshift: true
  pullPolicy: IfNotPresent
  defaultSSLCert: null
  http2ServerSide: "OFF"
  ingressClass: null
  ipam: false
  nsNamespace: null
  kubernetesURL: null
  license:
    accept: false
  logLevel: DEBUG
  logProxy: null
  loginFileName: null
  nodeSelector:
    key: null
    value: null
  nodeWatch: false
  crds:
    install: true
    retainOnDelete: false
  exporter:
    image: registry.connect.redhat.com/citrix/citrix-adc-metrics-exporter:latest
    ports:
      containerPort: 8888
    pullPolicy: IfNotPresent
    required: false
  coeConfig:
    distributedTracing:
      enable: false
      samplingrate: 100
    endpoint:
      server: null
    required: false
    timeseries:
      auditlogs:
        enable: false
      events:
        enable: false
      metrics:
        enable: false
        mode: avro
      port: 30002
    transactions:
      enable: false
      port: 30001 
