apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cic-operators
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/prashantjh/cic-index:latest
  displayName: CIC Operators
  publisher: Red Hat Partner
  updateStrategy:
    registryPoll:
      interval: 5m
